# Generated by Django 3.2.8 on 2021-11-06 00:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Symptoms', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraine'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('FATIGUE', 'Fatigue'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=79, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpermEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sperm encounter', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('type_of_encounter', models.CharField(blank=True, choices=[('UNPROTECTED', 'Unprotected'), ('PROTECTED', 'Protected'), ('INSEMINATION', 'Insemination')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('date_of_last_menstrual_period', models.DateField(default=datetime.date.today)),
                ('typical_flow_length', models.IntegerField()),
                ('typical_cycle_length', models.IntegerField()),
                ('typical_symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraine'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('CRAMPS', 'Cramps'), ('FATIGUE', 'Fatigue'), ('MOODSWINGS', 'Mood swings'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=97)),
                ('current_birth_control_method', multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('PILL', 'Pill'), ('MPILL', 'Minipill'), ('IUDH', 'Hormonal IUD'), ('IUDC', 'Copper IUD'), ('RING', 'Ring'), ('IMPLANT', 'Implant'), ('SHOT', 'Shot'), ('PATCH', 'Patch'), ('BARRIER', 'Barrier methods (condom, cervical cap, etc.)'), ('FAM', 'Fertility Awareness Method or Rythym Method'), ('WITHDRAWAL', 'Withdrawal')], max_length=72)),
                ('goal', models.CharField(choices=[('CONCEPTION', 'To get pregnant'), ('CONTRACEPTION', 'To avoid pregnancy'), ('CYCLEAWARENESS', 'Cycle awareness')], max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Period', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('cramps', models.CharField(blank=True, choices=[('NONE', 'None'), ('SLIGHT', 'Slight'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=100, null=True)),
                ('flow', models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy'), ('VHEAVY', 'Very heavy')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='mood', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('mood', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DEPRESSED', 'Depressed'), ('ANXIOUS', 'Anxious'), ('SAD', 'Sad'), ('NUMB', 'Numb'), ('IRRITABLE', 'Irritable'), ('ANGRY', 'Angry'), ('SENSITIVE', 'Sensitive'), ('SERENE', 'Serene'), ('HAPPY', 'Happy'), ('EXCITED', 'Excited'), ('ECSTATIC', 'Ecstatic')], max_length=82, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibidoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='libido', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('libido', models.CharField(blank=True, choices=[('NONE', 'None'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('High', 'High')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FertilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='fertility', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('pregnancy_test_result', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=100, null=True)),
                ('cerivcal_fluid_consistency', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STICKY', 'Sticky, dry'), ('CREAMY', 'Creamy'), ('STRETCHY', 'Stretchy, clear, slippery')], max_length=22, null=True)),
                ('basal_body_temperature', models.FloatField(blank=True, null=True)),
                ('luteinizing_hormone_level', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('period_started', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('period_ended', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraine'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('FATIGUE', 'Fatigue'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=79, null=True)),
                ('mood', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('DEPRESSED', 'Depressed'), ('ANXIOUS', 'Anxious'), ('SAD', 'Sad'), ('NUMB', 'Numb'), ('IRRITABLE', 'Irritable'), ('ANGRY', 'Angry'), ('SENSITIVE', 'Sensitive'), ('SERENE', 'Serene'), ('HAPPY', 'Happy'), ('EXCITED', 'Excited'), ('ECSTATIC', 'Ecstatic')], max_length=82, null=True)),
                ('energy', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EXHAUSTED', 'Exhausted'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('ENERGIZED', 'Energized')], max_length=37, null=True)),
                ('cramps', models.CharField(blank=True, choices=[('NONE', 'None'), ('SLIGHT', 'Slight'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=100, null=True)),
                ('flow', models.CharField(blank=True, choices=[('NONE', 'None'), ('LIGHT', 'Light'), ('MODERATE', 'Moderate'), ('HEAVY', 'Heavy'), ('VHEAVY', 'Very heavy')], max_length=100, null=True)),
                ('libido', models.CharField(blank=True, choices=[('NONE', 'None'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('High', 'High')], max_length=100, null=True)),
                ('sperm', models.CharField(blank=True, choices=[('UNPROTECTED', 'Unprotected'), ('PROTECTED', 'Protected'), ('INSEMINATION', 'Insemination')], max_length=100, null=True)),
                ('result', models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=100, null=True)),
                ('fluid', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STICKY', 'Sticky, dry'), ('CREAMY', 'Creamy'), ('STRETCHY', 'Stretchy, clear, slippery')], max_length=22, null=True)),
                ('bbt', models.FloatField(blank=True, null=True)),
                ('lh', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='energy level', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('energy', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EXHAUSTED', 'Exhausted'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('ENERGIZED', 'Energized')], max_length=37, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
