# Generated by Django 3.2.8 on 2021-11-04 03:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='period_end_date',
            new_name='period_ended',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='period_start_date',
            new_name='period_started',
        ),
        migrations.AlterField(
            model_name='event',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraines'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('FATIGUE', 'Fatigue'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=79, null=True),
        ),
    ]
