# Generated by Django 3.2.8 on 2021-11-04 15:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211104_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='symptoms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraine'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('FATIGUE', 'Fatigue'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=79, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typical_symptoms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('HEADACHE', 'Headaches'), ('MIGRAINE', 'Migraine'), ('BLOATING', 'Bloating'), ('SPOTTING', 'Spotting'), ('CRAMPS', 'Cramps'), ('FATIGUE', 'Fatigue'), ('MOODSWINGS', 'Mood swings'), ('PIMPLES', 'Pimples'), ('PAINOV', 'Ovulation pain'), ('PAINBACK', 'Back pain'), ('PAINAB', 'Abdominal pain')], max_length=97),
        ),
    ]
