# Generated by Django 3.2.8 on 2021-11-04 21:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211104_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fluid',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STICKY', 'Sticky, dry'), ('CREAMY', 'Creamy'), ('STRETCHY', 'Stretchy, clear, slippery')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cramps',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('SLIGHT', 'Slight'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sperm',
            field=models.CharField(blank=True, choices=[('UNPROTECTED', 'Unprotected'), ('PROTECTED', 'Protected'), ('INSEMINATION', 'Insemination')], max_length=100, null=True),
        ),
    ]
