# Generated by Django 3.2.8 on 2021-11-04 21:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211104_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='energy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('EXHAUSTED', 'Exhausted'), ('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('ENERGIZED', 'Energized')], max_length=37, null=True),
        ),
    ]
